services:
  - type: web
    name: eriwaspecials
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    envVars:
      - key: PORT
        value: 8080
