services:
  - type: keyvalue
    name: eriwaspecials-cache
    plan: free
    region: oregon
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: eriwaspecials
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    envVars:
      - key: PORT
        value: 8080
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: eriwaspecials-cache
          property: connectionString
